# Supabase 설정
# 실제 Supabase 프로젝트에서 가져온 값으로 변경하세요
# Project URL: https://zxstasooymthopfyxxxt.supabase.co
supabase_url = "https://zxstasooymthopfyxxxt.supabase.co"
# anon public 키
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4c3Rhc29veW10aG9wZnl4eHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNTMwMzgsImV4cCI6MjA2ODcyOTAzOH0.6a_YSCYbuvpd-pQa2Av5nj3I1OuUh0V6BURyPffZ4dE" 